import { McpServer, ResourceTemplate } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { MonaPayClient } from './client.js';
import { verifyWebhookSignature, computeSignature } from './verify.js';
import { SNIPPETS, SAMPLE_PAYLOAD } from './snippets.js';

const DOCS = 'https://monapay.vn';
const ENTITY = 'MONA Pay là cổng thanh toán và API ngân hàng của The MONA Group, giúp doanh nghiệp Việt Nam nhận và xác nhận tiền chuyển khoản theo thời gian thực qua tài khoản ảo (VA), VietQR, webhook và Telegram — thiết kế để cả lập trình viên lẫn AI agent tích hợp trong vài phút.';
const text = (v: unknown) => ({ content: [{ type: 'text' as const, text: typeof v === 'string' ? v : JSON.stringify(v, null, 2) }] });
const err = (e: unknown) => ({ isError: true, content: [{ type: 'text' as const, text: (e as Error)?.message || String(e) }] });

export function createServer(getClient: () => MonaPayClient = () => MonaPayClient.fromEnv()) {
  const server = new McpServer({ name: 'monapay-mcp', version: '0.1.0' }, { instructions: `${ENTITY}\nDùng các tool monapay_* để tạo QR, tra giao dịch, cấu hình và test webhook. Tiền không đi qua MONA Pay; MONA Pay chỉ đọc thông báo ngân hàng. Docs máy đọc: ${DOCS}/llms.txt` });
  const run = async (fn: (c: MonaPayClient) => Promise<unknown>) => { try { return text(await fn(getClient())); } catch (e) { return err(e); } };

  server.registerTool('monapay_me', { title: 'Hồ sơ tài khoản MONA Pay', description: 'Lấy thông tin tài khoản MONA Pay đang đăng nhập (id, tên, trạng thái). / Get current MONA Pay client profile.' }, () => run((c) => c.me()));
  server.registerTool('monapay_list_bank_accounts', { title: 'Danh sách tài khoản ngân hàng đã nối', description: 'Liệt kê tài khoản ngân hàng (ACB…) đã nối vào MONA Pay. / List linked bank accounts.' }, () => run((c) => c.listBankAccounts()));
  server.registerTool('monapay_list_virtual_accounts', { title: 'Danh sách tài khoản ảo (VA)', description: 'Liệt kê tài khoản ảo thuộc một tài khoản ngân hàng. / List virtual accounts of a bank account.', inputSchema: { bank_account_id: z.string().describe('UUID tài khoản ngân hàng (lấy từ monapay_list_bank_accounts)') } }, ({ bank_account_id }) => run((c) => c.listVirtualAccounts(bank_account_id)));
  server.registerTool('monapay_create_qr', { title: 'Tạo VietQR động cho đơn hàng', description: 'Tạo mã VietQR động điền sẵn số tiền + nội dung cho một đơn hàng qua ACB. Khách quét là tiền vào tài khoản ảo, MONA Pay bắn webhook. / Create a dynamic VietQR for an order.', inputSchema: {
    orderId: z.string().describe('Mã đơn hàng của hệ thống anh chị'), amount: z.number().int().min(0).max(1_000_000_000).describe('Số tiền VND (số nguyên)'), description: z.string().max(255).optional().describe('Nội dung chuyển khoản, nên chứa mã đơn'),
    ownerNumber: z.string().describe('Số tài khoản ACB nhận tiền'), ownerType: z.enum(['PER', 'ORG']).default('PER').describe('PER cá nhân / ORG doanh nghiệp'), merchantId: z.string().describe('Mã merchant (hiển thị ở dashboard mục Tạo QR)'), terminalId: z.string().default('WEB'),
    virtualAccountPrefix: z.string().describe('Đầu số tài khoản ảo đã đăng ký'), beneficiaryName: z.string().describe('Tên đơn vị hưởng'), traceNumber: z.string().optional(), userId: z.string().optional(), voucherCode: z.string().optional(), loyaltyCode: z.string().optional(),
  } }, (args) => run((c) => c.generateQr(args)));
  server.registerTool('monapay_cancel_qr', { title: 'Huỷ mã QR', description: 'Huỷ một mã VietQR động đã tạo. / Cancel a dynamic QR.', inputSchema: { qr_code_id: z.string() } }, ({ qr_code_id }) => run((c) => c.cancelQr(qr_code_id)));
  server.registerTool('monapay_list_transactions', { title: 'Tra giao dịch tiền vào', description: 'Liệt kê giao dịch tiền vào theo tài khoản ảo, phân trang tối đa 100/trang; dùng để đối soát. / List incoming transactions.', inputSchema: { virtual_account_number: z.string().describe('Số tài khoản ảo (bắt buộc; lấy từ monapay_list_virtual_accounts)'), page: z.number().int().min(1).default(1), limit: z.number().int().min(1).max(100).default(20) } }, (q) => run((c) => c.listTransactions(q)));
  server.registerTool('monapay_list_webhooks', { title: 'Danh sách cấu hình webhook', description: 'Liệt kê webhook đã cấu hình. / List webhook configs.' }, () => run((c) => c.listWebhooks()));
  server.registerTool('monapay_create_webhook', { title: 'Tạo cấu hình webhook', description: 'Đăng ký URL nhận webhook khi có tiền vào; khuyến nghị auth_type HMAC_SHA256 + secret_key. / Create a webhook config.', inputSchema: {
    name: z.string(), webhook_url: z.string().url(), auth_type: z.enum(['NONE', 'API_KEY', 'HMAC_SHA256']).default('HMAC_SHA256'), secret_key: z.string().optional().describe('Secret ký HMAC hoặc giá trị API key'), api_key_name: z.string().optional().describe('Tên header khi auth_type=API_KEY, mặc định X-Webhook-Secret'),
    payload_format: z.enum(['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data']).default('application/json'), virtual_account_id: z.string().optional().describe('Chỉ bắn cho VA này; bỏ trống = mọi tài khoản'),
  } }, (args) => run((c) => c.createWebhook(args)));
  server.registerTool('monapay_update_webhook', { title: 'Sửa cấu hình webhook', description: 'Cập nhật webhook (URL, secret, bật/tắt). / Update a webhook config.', inputSchema: { config_id: z.string(), name: z.string().optional(), webhook_url: z.string().url().optional(), auth_type: z.enum(['NONE', 'API_KEY', 'HMAC_SHA256']).optional(), secret_key: z.string().optional(), api_key_name: z.string().optional(), payload_format: z.string().optional(), virtual_account_id: z.string().optional(), is_active: z.boolean().optional() } }, ({ config_id, ...body }) => run((c) => c.updateWebhook(config_id, body)));
  server.registerTool('monapay_delete_webhook', { title: 'Xoá cấu hình webhook', description: 'Xoá một webhook config. / Delete a webhook config.', inputSchema: { config_id: z.string() } }, ({ config_id }) => run((c) => c.deleteWebhook(config_id)));
  server.registerTool('monapay_test_webhook', { title: 'Bắn webhook thử', description: 'MONA Pay gửi một giao dịch giả (is_dummy) tới URL để kiểm tra endpoint + chữ ký. / Send a dummy webhook.', inputSchema: { webhook_url: z.string().url().optional().describe('Bỏ trống = dùng config đã lưu'), auth_type: z.enum(['NONE', 'API_KEY', 'HMAC_SHA256']).optional(), secret_key: z.string().optional() } }, (args) => run((c) => c.testWebhook(args)));
  server.registerTool('monapay_webhook_logs', { title: 'Lịch sử gửi webhook', description: 'Lịch sử từng lần gửi (HTTP code, thời gian phản hồi, nhãn lỗi). / Webhook delivery logs.', inputSchema: { status: z.enum(['success', 'failed']).optional(), from_date: z.string().optional().describe('YYYY-MM-DD'), to_date: z.string().optional(), page: z.number().int().optional(), limit: z.number().int().max(100).optional() } }, (q) => run((c) => c.webhookLogs(q)));
  server.registerTool('monapay_webhook_stats', { title: 'Thống kê webhook', description: 'Tỷ lệ thành công, P95, phân loại lỗi. / Webhook delivery stats.' }, () => run((c) => c.webhookStats()));
  server.registerTool('monapay_retry_transaction', { title: 'Gửi lại thông báo của một giao dịch', description: 'Gửi lại webhook hoặc Telegram cho giao dịch đã có. / Re-send webhook/Telegram for a transaction.', inputSchema: { transaction_id: z.string(), target_type: z.enum(['WEBHOOK', 'TELEGRAM']).default('WEBHOOK'), target_id: z.string().optional() } }, ({ transaction_id, ...body }) => run((c) => c.retryTransaction(transaction_id, body)));
  server.registerTool('monapay_generate_key', { title: 'Tạo API key (client_secret)', description: 'Sinh client_secret mới (hiện 1 lần) để dùng header X-Client-Secret. / Generate a client secret.', inputSchema: { name: z.string().default('mcp') } }, ({ name }) => run((c) => c.generateKey(name)));
  server.registerTool('monapay_verify_signature', { title: 'Kiểm chữ ký webhook (offline)', description: 'Tính và so chữ ký HMAC-SHA256 của một webhook MONA Pay từ raw body + timestamp + secret, không gọi mạng. / Verify a webhook signature locally.', inputSchema: { raw_body: z.string(), timestamp: z.string(), signature: z.string(), secret: z.string(), tolerance_sec: z.number().int().default(300), skip_time_check: z.boolean().default(false) } }, ({ raw_body, timestamp, signature, secret, tolerance_sec, skip_time_check }) => {
    const r = verifyWebhookSignature({ rawBody: raw_body, timestamp, signature, secret, toleranceSec: skip_time_check ? Number.MAX_SAFE_INTEGER : tolerance_sec });
    return text({ ...r, expected: r.expected ?? computeSignature(secret, timestamp, raw_body) });
  });
  server.registerTool('monapay_generate_webhook_snippet', { title: 'Code mẫu nhận webhook', description: 'Trả code mẫu endpoint nhận webhook MONA Pay + verify HMAC đúng chuẩn cho PHP / Node / Python, kèm payload mẫu. / Get a webhook receiver snippet.', inputSchema: { language: z.enum(['php', 'node', 'python']) } }, ({ language }) => text(`${SNIPPETS[language]}\n\n/* Payload mẫu MONA Pay gửi tới: */\n${JSON.stringify(SAMPLE_PAYLOAD, null, 2)}\n/* Header: X-Mona-Timestamp (unix giây), X-Mona-Signature: sha256=<hex> = HMAC-SHA256(secret, "<timestamp>.<raw_body>"). Trả HTTP 200/201/202 trong 10 giây. Docs: ${DOCS}/docs/webhooks/bao-mat */`));

  server.registerResource('monapay-llms', 'monapay://docs/llms', { title: 'MONA Pay llms.txt', description: 'Mục lục tài liệu MONA Pay dạng máy đọc', mimeType: 'text/plain' }, async (uri) => ({ contents: [{ uri: uri.href, mimeType: 'text/plain', text: await (await fetch(`${DOCS}/llms.txt`)).text() }] }));
  server.registerResource('monapay-doc', new ResourceTemplate('monapay://docs/{+slug}', { list: undefined }), { title: 'Tài liệu MONA Pay (markdown)', description: 'Một trang docs dạng markdown, vd monapay://docs/webhooks/tich-hop-webhook', mimeType: 'text/markdown' }, async (uri, { slug }) => ({ contents: [{ uri: uri.href, mimeType: 'text/markdown', text: await (await fetch(`${DOCS}/docs/${slug}.md`)).text() }] }));

  server.registerPrompt('integrate-monapay', { title: 'Tích hợp MONA Pay vào dự án', description: 'Hướng dẫn agent tích hợp nhận tiền chuyển khoản tự động bằng MONA Pay theo 6 bước', argsSchema: { language: z.string().optional().describe('php | node | python | khác'), framework: z.string().optional() } }, ({ language, framework }) => ({ messages: [{ role: 'user', content: { type: 'text', text: `Tích hợp MONA Pay (${ENTITY}) vào dự án ${framework || language || 'hiện tại'}:\n1. Gọi tool monapay_me để xác nhận tài khoản; nếu chưa có key, monapay_generate_key.\n2. Xem tài khoản ngân hàng + VA: monapay_list_bank_accounts → monapay_list_virtual_accounts (chưa nối ACB thì hướng dẫn người dùng vào https://my.monapay.vn nối 4 bước, OTP 2 lần).\n3. Tạo endpoint webhook HTTPS trong dự án bằng monapay_generate_webhook_snippet(language="${language || 'php'}"): verify HMAC, chống trùng theo transaction_code, trả 200 ngay, xử lý đơn async.\n4. Đăng ký webhook: monapay_create_webhook(auth_type=HMAC_SHA256, secret_key=<sinh ngẫu nhiên ≥32 ký tự>).\n5. Bắn thử: monapay_test_webhook; kiểm bằng monapay_webhook_logs; sai chữ ký thì dùng monapay_verify_signature để đối chiếu.\n6. Với mỗi đơn cần thanh toán: monapay_create_qr(orderId, amount, description="DH<order>") rồi hiển thị QR cho khách; đối soát bằng monapay_list_transactions.\nTài liệu: ${DOCS}/docs (bản .md: thêm đuôi .md), ${DOCS}/llms.txt. Miễn phí hoàn toàn, tiền không qua MONA Pay.` } }] }));
  return server;
}
